"""Create Database

Revision ID: 7691d1ee9a6e
Revises: 
Create Date: 2023-08-29 13:05:30.411239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7691d1ee9a6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('customers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('phone', sa.String(length=255), nullable=True),
                    sa.Column('outlet_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('employees',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('username', sa.String(length=255), nullable=True),
                    sa.Column('outlet_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
                    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('where_to_id', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('performer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['customers.id'], ),
                    sa.ForeignKeyConstraint(['performer_id'], ['employees.id'], ),
                    sa.ForeignKeyConstraint(['where_to_id'], ['outlets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('visits',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=True),
                    sa.Column('performer_id', sa.Integer(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('where_to_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['customers.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.ForeignKeyConstraint(['performer_id'], ['employees.id'], ),
                    sa.ForeignKeyConstraint(['where_to_id'], ['outlets.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('order_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('orders')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('outlets')
    # ### end Alembic commands ###
